feat(fe): Header & Toast 완성
skkuding/skkuzzim pull request #19
Opened 2023-01-12 10:22 UTC by EliseCho13

헤더랑 토스터 완성했습니다
close #8 
close #10

2023-01-12 12:30 UTC, Taerogrammer requested changes

2023-01-12 12:30 UTC, Taerogrammer commented on frontend/src/components/Header.vue
> +    </div>
star-time과 end-time을 추가하면 ``가 나타납니다.
<img width="892" alt="image" src="https://user-images.githubusercontent.com/104834390/212066646-7e0ac72b-ad91-424a-8583-73ad97996002.png">

2023-01-12 14:49 UTC, conakoo commented
PR #17 이 close되고 merge되면서 conflict가 났을꺼에요. 
해당 conflict 해결해주시고 커밋 올려주세요 😄

```bash
# 먼저 main 브랜치 내용을 현재 브랜치로 가져와주세요
git merge origin/main

# conflict 메시지가 뜰텐데 vscode 왼쪽 브랜치 모양을 선택하고
# Merge Changes 에 있는 파일의 conflict 부분을 모두 해결해주세요!
# current와 incoming 중 남기고자 하는 코드를 선택해주면 됩니다. (ex. accept incoming)
# base.css와 main.css 같은 경우 + 버튼을 누르고 delete file 선택

# conflict 해결 후 모든 파일을 staged 상태로 올리고 commit -> git push까지 진행하시면 됩니다.

```

2023-01-13 05:34 UTC, eunnbi commented on frontend/src/components/Header.vue
> +  <div class="headerWrapper">
`div` 대신 `header` 태그 (semantic tag)를 쓰는 건 어떨까요??

2023-01-14 12:23 UTC, goo314 requested changes

2023-01-14 12:23 UTC, conakoo commented on frontend/package.json
> +    "font-awesome": "^4.7.0",
dependencies의 `fontawesome` 관련 다 지워주세요! 
unplugin-icon에서 자동적으로 설치하면서 아래 devDependencies에 추가됩니당 😃

2023-01-14 12:23 UTC, conakoo commented on frontend/src/components/Toast.vue
> +import iconRegularCircleCheck from '~icons/fa6-regular/circle-check'
요부분도 우리 프로젝트 unplugin icon 사용 방법에 맞춰 수정해주세요
https://www.notion.so/6b2dc50339ae4e56ad6f00ebe8004ce0#fe310a7165194d38a8d9c236821696dc

아이콘의 이름은 Icon~~으로 시작해주세요! ex. `iconRegularCircleCheck` ➡️  `IconCircleCheck`

2023-01-14 12:23 UTC, goo314 commented on frontend/src/components/Header.vue
> +  width: 100%;
`width` 값이 2번 들어갔어요! 하나는 지워주세요 😃

2023-01-14 12:23 UTC, goo314 commented on frontend/src/components/Header.vue
> +}>();
props 를 1개 또는 2개로 묶으면 좋을 것 같아요! 
"2023년 1월"만 받거나 "1월 23일 12:00~12:30"만 있어서?

2023-01-14 12:52 UTC, goo314 commented on frontend/src/components/Header.vue
> +}>();
참고로 vueuse의 `useDateFormat`을 사용하면 유용할 것 같아요!
https://vueuse.org/shared/usedateformat/#usedateformat

2023-01-21 08:10 UTC, EliseCho13 commented on frontend/src/components/Header.vue
> +}>();
음 일단 useDateFormat을 써 보긴 했는데...쓰기 전이 훨씬 더 입력이 간단하지 않나요? 시간 입력만 받아야 하는 곳에서도 date의 폼 형식을 맞추기 위해 날짜까지 넣어야 하는 거 같아서요

2023-01-21 08:32 UTC, dotoleeoak commented on frontend/src/components/Header.vue
> +}>();
@EliseCho13 아마 성현이가 의도한 건 출력을 `useDateFormat`으로 하라고 한 것 같네요!
props로 받아오는 건 number 또는 Date 객체로 받아오는 게 좋을 것 같은데, 개인적인 의견으로는 Date 객체로 받아오면 `year`, `month`, `day` 같은 props는 필요 없이 `startTime`, `endTime` 두 props만 받아와도 돼서 interface가 조금 더 깔끔해질 것 같아요.

```suggestion
const props = defineProps<{
  startTime: Date;
  endTime: Date;
}>();
```

그러면 아래처럼 `useDateFormat`을 사용해서 template에 보여줄 수 있겠죠?

```ts
const startDate = useDateFormat(props.startTime, "M월 D일 HH시 mm분");
const endDate = useDateFormat(props.endTime, "HH시 mm분");
```

```vue
<div>{{ startDate }} ~ {{ endDate }}</div>
```

2023-01-21 08:41 UTC, EliseCho13 commented on frontend/src/components/Header.vue
> +}>();
다른 브랜치에 잘못 commit해서...8-header로 풀 해와서 커밋하려 했는데 뭐가 잘못됐는지 수정한 내역이 날아가서 ㅠㅠ 다른 부분은 다 새로 고쳤는데, 그냥 이 부분은 그대로 둔 채로 커밋하겠습니다

2023-01-21 08:48 UTC, goo314 commented on frontend/src/assets/base.css
> +  --vt-c-indigo: #2c3e50;
src/assets/base.css 파일 지워주세요!

2023-01-21 08:52 UTC, goo314 commented on frontend/src/assets/base.css
> +  --vt-c-indigo: #2c3e50;
아 그리고 Icon이름에서 collection 이름은 빼주세요! 
```
IconCicle import '~icons/fa6-regular/cicle' ⭕  

IconRegularCicle import '~icons/fa6-regular/cicle' ❌ 
```

2023-01-26 11:25 UTC, eunnbi requested changes

2023-01-26 11:25 UTC, eunnbi commented on frontend/src/components/Toast.vue
> +  border-radius: 20px;
`border-radius` 값을 `8px`로 수정해주세요!

2023-01-26 11:25 UTC, eunnbi commented on frontend/src/components/Toast.vue
> +  font-size: 20px;
`styles` 폴더 내 `theme` 파일 내 `FONT_SIZE` 객체랑 `v-bind` 이용해서 수정해주세요!

2023-01-26 11:25 UTC, eunnbi commented on frontend/src/components/Toast.vue
> +  <div class="toastWrapper">
`kebab-case`로 수정해주세요!

2023-01-26 11:25 UTC, eunnbi commented on frontend/src/components/Toast.vue
> +    <div class="toastMessage">{{ msg }} 완료되었습니다!</div>
"완료되었습니다!"를 지우고 전체 메시지를 `msg props`로 받아오는 것은 어떨까요?

2023-01-26 11:33 UTC, eunnbi commented on frontend/src/components/Toast.vue
> +    <div class="toastMessage">{{ msg }} 완료되었습니다!</div>
`div` 대신 `p` 태그를 사용하는 건 어떨까요?

2023-01-26 11:36 UTC, eunnbi requested changes

2023-01-26 11:36 UTC, eunnbi commented on frontend/src/components/Toast.vue
> +  background-color: #8dc63f;
`styles` 폴더 내 `theme` 파일 내 `FONT_SIZE` 및 `COLOR` 객체랑 `v-bind` 이용해서 수정해주세요!

2023-01-26 11:42 UTC, eunnbi requested changes

2023-01-26 11:42 UTC, eunnbi commented on frontend/src/components/Header.vue
> +  font-size: 32px;
`styles` 폴더 내 `theme` 파일 내 `FONT_SIZE` 객체랑 `v-bind` 이용해서 수정해주세요!

2023-01-26 12:35 UTC, goo314 requested changes

2023-01-26 12:35 UTC, goo314 commented on frontend/src/App.vue
> +  <Header dayTime="2023년 1월" class="header"></Header>
class 지워주세요!

2023-01-26 12:35 UTC, goo314 commented on frontend/src/components/Header.vue
> +        </a>
아이콘과 글자 위치가 맞지 않은 것 같아요!

<img width="626" alt="image" src="https://user-images.githubusercontent.com/62930375/214836442-7cd678d6-4aeb-4d9a-9fae-285a971c584a.png">

2023-01-26 12:35 UTC, goo314 commented on frontend/src/components/Toast.vue
> +<style scoped>
z-index값 줘서 페이지 상단에 오게 해주세요!

2023-01-26 13:12 UTC, eunnbi approved these changes

2023-01-26 13:16 UTC, goo314 approved these changes

2023-01-26 13:21 UTC, merged