feat(fe): add button
skkuding/skkuzzim pull request #20
Opened 2023-01-12 12:16 UTC by Taerogrammer

버튼 구현
close #12

2023-01-12 12:22 UTC, EliseCho13 reviewed
font-weight: bold는 공통적으로 있으니 공통스타일로 주어도 좋을 거 같아요
비슷한 버튼별로 컴포넌트를 좀 더 분리해서 만들었다면 const backgroundColor에서 리턴하는 게 좀 더 짧았을 테지만, 이것도 나쁘진 않은 거 같습니다

2023-01-12 14:49 UTC, goo314 commented
PR #17 이 close되고 merge되면서 conflict가 났을꺼에요. 
해당 conflict 해결해주시고 커밋 올려주세요 😄

```bash
# 먼저 main 브랜치 내용을 현재 브랜치로 가져와주세요
git merge origin/main

# conflict 메시지가 뜰텐데 vscode 왼쪽 브랜치 모양을 선택하고
# Merge Changes 에 있는 파일의 conflict 부분을 모두 해결해주세요!
# current와 incoming 중 남기고자 하는 코드를 선택해주면 됩니다. (ex. accept incoming)
# base.css와 main.css 같은 경우 + 버튼을 누르고 delete file 선택

# conflict 해결 후 모든 파일을 staged 상태로 올리고 commit -> git push까지 진행하시면 됩니다.

```

2023-01-14 11:35 UTC, goo314 requested changes

2023-01-14 11:35 UTC, goo314 commented on frontend/src/components/Button.vue
> +});
이부분은 theme.ts 파일의 `COLOR` 을 사용하면 더 편리할 거에요!
공통된 속성은 class로 정의해주고 white인 경우만 다른 class 적용하면 간단해질 것 같아요 😁

```html
<template>
  <button ... :class="color==='white'? 'white-button': 'colored-button'">...</button>
</template>

<style>

/* ... */

.white-button {
  background-color: white;
  border: 2px solid v-bind(COLOR.gray);
}

.colored-button {
  background-color: v-bind("COLOR[props.color]");
  border-style: hidden;
  color: "white";
}
</style>
```

2023-01-14 11:35 UTC, goo314 commented on frontend/src/components/Button.vue
> +  padding-left: 20px;
`padding: [세로방향] [가로방향]` 하나로 묶어서 적으면 좋을 것 같아요!

2023-01-14 11:43 UTC, goo314 commented on frontend/src/components/Button.vue
> +});
아마 props.color 쪽에서 type error가 날 수 있을텐데
(props.color는 모든 string으로 정의 ↔️ COLOR의 key값은 blue, dark-red, .... 정해져 있어서)

props.color의 type 부분을 `keyof typeof COLOR`로 정의해주면 해결됩니당

2023-01-15 11:49 UTC, goo314 commented
해당 PR은 제가 이어서 하겠습니다 ! 😊

2023-01-15 17:43 UTC, goo314 approved these changes

2023-01-15 17:51 UTC, goo314 commented
`git merge origin/main` 

실행 후 lefthook인 prettier와 eslint 검사에서 걸려서

`npx prettier --write .` 

로 틀린 문법 싹 고쳐서 file changed가 많아졌네요. (이게 맞는건가?)

결론은,, Button.vue와 theme.ts, style.css 수정했습니다!
- Button.vue : 코드 리뷰 resolve + hover, active css 추가
- theme.ts : dark-gray, white 색상 추가
- style.css : font-size default 값으로 16px 추가

2023-01-16 06:10 UTC, eunnbi approved these changes

2023-01-16 10:58 UTC, merged