3 feature 전체 예약 정보 조회
skkuding/skkuzzim pull request #39
Opened 2023-01-16 05:14 UTC by jspark2000

## 구현
---
전체 예약 정보 조회 완성

close #3

2023-01-16 07:43 UTC, SH9480P requested changes
확인해주세요~~~

2023-01-16 07:43 UTC, SH9480P commented on backend/src/prisma/prisma.service.ts
> +import { PrismaClient } from '@prisma/client';
; 지워주세요~

2023-01-16 07:43 UTC, SH9480P commented on backend/src/prisma/prisma.service.ts
> +import { PrismaClient } from '@prisma/client';
ㅇㄴㄷㅎㄴㄷㅎㄴㄷㅎ

2023-01-16 08:24 UTC, jspark2000 commented on backend/src/prisma/prisma.service.ts
> +import { PrismaClient } from '@prisma/client';
수정했습니다!

2023-01-16 13:23 UTC, goo314 commented
프론트엔드 파일 conflict 해결했습니다! 
`git pull`로 해당 커밋 반영해서 작업 이어서 해주세요 😁

2023-01-17 14:40 UTC, k1g99 approved these changes

2023-01-17 15:55 UTC, Hyeongrok1 approved these changes

2023-01-17 15:55 UTC, Hyeongrok1 commented on backend/src/reservation/reservation.service.ts
> +    })
데이터베이스에서 프리즈마를 이용해서 예약 정보를 읽어오는 코드를 prisma.service.ts에서 따로 구현하지 않고 ReservationService에서 다 구현한 이유가 궁금합니다!

2023-01-18 04:42 UTC, jspark2000 commented on backend/src/reservation/reservation.service.ts
> +    })
저는 Nest의 경우 모듈식 구성을 통해 비슷한 기능들을 묶는 일종의 캡슐화를 할 수 있도록 만들어졌다고 알고있습니다.
이에 따라 "DB에서 예약 정보를 불러오는 기능"을 prisma 모듈에 포함시킬지 아니면 reservation 모듈에 포함시킬지 선택해야합니다.

프로젝트 베이스 코드를 보면 현재 prisma 모듈의 경우 아래처럼 db에 연결하는 역할을 이미 수행하고 있습니다.
```typescript
@Injectable()
export class PrismaService extends PrismaClient {
  constructor(private config: ConfigService) {
    super({
      datasources: {
        db: {
          url: config.get('DATABASE_URL')
        }
      }
    })
  }
}
```
prisma 모듈의 역할을 "db와 관련된 모든 작업"으로 본다면 prisma 모듈에 예약 정보를 읽어오는 코드를 작성할 수도 있지만,
저는 "DB에서 예약 정보를 불러오는 기능"이 prisma 모듈과 reservation 모듈중 후자에 더 가깝다고 생각하여 reservation.service.ts 파일에 작성했습니다!

다른 이유로는 현재는 예약 관련 서비스 밖에 없지만, 댓글기능 등 다른 여러가지 기능이 추가된다면, prisma 모듈 내에 서로 다른 테이블의 정보를 가져오는 코드들이 섞이고 코드가 엄청 길어지게 됩니다. 이는 가독성 및 유지보수 측면에서 불리하다고 생각하여 reservation 모듈에 작성하는 것이 좋을 것 같다고 생각했습니다!

2023-01-18 15:36 UTC, BEpaul approved these changes
고생 많으셨습니다!!

2023-01-19 07:20 UTC, SH9480P commented
migration 파일을 굳이 지우신 이유가 있나요?

2023-01-19 07:22 UTC, dotoleeoak commented
https://github.com/skkuding/skkuzzim/pull/39/commits/0eb445034cc1a5296ccad213fb33f5e86fd9f269
이 커밋 revert 부탁드릴게요!

2023-01-19 07:27 UTC, jspark2000 commented
> migration 파일을 굳이 지우신 이유가 있나요?

migrations 폴더 복구 하려고 했는데 잘 모르겠습니다..

2023-01-19 07:36 UTC, jspark2000 commented
> migration 파일을 굳이 지우신 이유가 있나요?

해결했습니다!

2023-01-19 07:46 UTC, SH9480P commented
Commit하실 때 convention 지켜주세요!
[CONTRIBUTING.md](https://github.com/skkuding/skkuzzim/blob/main/CONTRIBUTING.md) 읽어주세요~

2023-01-19 07:58 UTC, jspark2000 commented
확인했습니다!

2023-01-19 09:33 UTC, SH9480P requested changes

2023-01-19 09:33 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +      },
11시부터 13시까지 조회한다고 가정했을 때,
09시부터 14시까지인 예약 건은 아예 조회가 안 되네요.

2023-01-19 12:53 UTC, SH9480P reviewed
확인했습니다~~ merge해주세요! @jspark2000

2023-01-19 12:54 UTC, SH9480P approved these changes

2023-01-19 13:15 UTC, SH9480P requested changes

2023-01-19 13:15 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +    const { startTime, endTime } = reservationDTO
반환값 타입 지정 해주세요!

2023-01-19 13:40 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +    const { startTime, endTime } = reservationDTO
`getAllReservations` 이외에도 타입 추론 안되는 함수들 있으면 타입 지정 추가해주세요~

2023-01-20 13:58 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +}
response dto도 request dto처럼 별도의 파일로 만들어서 import하는 것은 어떨까요?

2023-01-23 05:19 UTC, jspark2000 commented on backend/src/reservation/reservation.service.ts
> +}
좋은거 같습니다!

2023-01-23 11:21 UTC, SH9480P approved these changes
고생하셨습니다~~ 👍 🥇 🐇 🏖️ merge 부탁드릴게요!

2023-01-23 14:11 UTC, merged