feat(BE): specific table view
skkuding/skkuzzim pull request #43
Opened 2023-01-16 08:01 UTC by JungangHighschool

상세 정보 조회 API 구현
Close #40

2023-01-17 14:26 UTC, k1g99 reviewed
확인 부탁드립니다~!~!

2023-01-17 14:26 UTC, k1g99 commented on backend/src/reservation/reservation.controller.ts
> +    console.log(startTime, endTime)
배포단계에서는 주석처리나 삭제가 필요할 것 같습니다!

2023-01-17 14:26 UTC, k1g99 commented on backend/src/reservation/reservation.service.ts
> +    const dbresults = await this.prismaService.reservation.findMany({
파라미터로 전달되는 start와 end사이의 시간 간격이 30분으로 고정되어있는 것으로 이해했는데

예를 들어 `start = 2023-02-02T13:00:00` ~ `end = 2023-02-02T13:30:00` 으로 되어있고,
만약 저장된 일정이 `2023-02-02T13:00:00` ~ `2023-02-02T15:00:00` 으로 되어있다면, 
해당 일정을 쿼리하는 게 가능한가요??

(제가 잘못 이해했을 수도 있습니다;;;)

2023-01-18 04:53 UTC, JungangHighschool commented on backend/src/reservation/reservation.controller.ts
> +    console.log(startTime, endTime)
옙, 수정하겠습니다!

2023-01-18 04:59 UTC, JungangHighschool commented on backend/src/reservation/reservation.service.ts
> +    const dbresults = await this.prismaService.reservation.findMany({
그 부분을 생각 못했네요;; 수정하겠습니다!

2023-01-19 09:34 UTC, SH9480P commented
PR 설명 작성해주세요~

2023-01-19 13:27 UTC, SH9480P requested changes

2023-01-19 13:27 UTC, SH9480P commented on backend/src/reservation/reservation.module.ts
> +import { Get, Module } from '@nestjs/common'
Get 지워주세요

2023-01-19 13:27 UTC, SH9480P commented on backend/src/reservation/reservation.controller.ts
> +}
async, await 붙여주세요

2023-01-19 13:27 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +  async specificReservation(start: string, end: string) {
- `specificReservation` 메서드 반환값 타입 지정 해주세요!
- 함수 이름은 동사로 시작하는게 더 좋아보여요. getSpecificReservation은 어떨까요?

2023-01-19 13:27 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +    const dbresults = await this.prismaService.reservation.findMany({
- 변수 이름은 camelCase로 해주세요.
- `dbresults` 말고 더 가독성 있는 이름은 어떨까요?

2023-01-21 16:24 UTC, SH9480P requested changes
이 부분만 변경해주시면 문제 없이 merge 가능할 것 같아요~ 화이팅~~

2023-01-21 16:24 UTC, SH9480P commented on backend/package.json
>      "rxjs": "^7.2.0"
`npm install pnpm` 명령어로 설치하신 것 같네요.
`npm i -g pnpm`으로 설치하시고, package.json dependencies에 있는 pnpm은 지워주세요.

마찬가지로 package-lock.json도 npm install로 생성된 것 같네요. 
pnpm 사용 시 필요 없는 파일입니다. 지워주세요!

2023-01-21 16:24 UTC, SH9480P commented on backend/src/reservation/reservation.controller.ts
> +  }
getSpecificReservation으로 변경해주세요~

2023-01-21 16:24 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +        }
API 명세서대로 member's'로 바꿔주세요

2023-01-21 16:24 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +          }
2시--2시 30분의 time block을 클릭했다고 가정해봅시다...
이 코드대로라면 예약의 startTime과 endTime이 2시와 2시 반 사이에 있는 예약 건만 조회되겠죠.
그러나 우리는 2시--2시 30분을 **포함하는 모든** 예약 건을 조회해야 합니다. 
이를테면, 1시에서 3시까지인 예약이 조회되어야 한다는 거죠.

2023-01-26 11:07 UTC, SH9480P requested changes
# package-lock.json 삭제해주세요~~~

2023-01-26 11:07 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +      },
1시 ~ 1시 30분 조회하는 경우에 12 ~ 1시 예약이 조회되면 안되겠죠?
마찬가지로 1시 30분 ~ 3시 예약도 조회되면 안됩니다.
쿼리 수정해주세요~

2023-01-26 12:28 UTC, SH9480P approved these changes
수고하셨습니다~ merge해주세요!

2023-01-26 13:47 UTC, merged