feat(be): add reservation create service
skkuding/skkuzzim pull request #45
Opened 2023-01-16 15:35 UTC by k1g99

## 예약 생성 API 구현

### 세부내용
* HTTP 메소드: POST
* URL: ~/reservation

### Request-format
```json
{
  "creator": "김감자", 
  "club": "스꾸딩",
  "startTime": "2023-01-16T15:00:00",
  "endTime": "2023-01-16T18:00:00",
  "purpose": "미팅",
  "member": ["김감자", "김고구마", "김옥수수"]
}
```
* request 보낼 때 creator는 member에 포함되어야합니다.

### 확인사항
* 만약 createTime이나 updateTime을 활용한다면 TIMEZONE 설정관련 논의가 필요해 보입니다. 
  ```json
  {
    "id": 11,
    "creator": "김감자",
    "club": "스꾸딩",
    "startTime": "2023-01-16T06:00:00.000Z",
    "endTime": "2023-01-16T09:00:00.000Z",
    "purpose": "미팅",
    "createTime": "2023-01-16T15:02:22.287Z",
    "updateTime": "2023-01-16T15:02:22.287Z"
  }
  ```

Closes #1

2023-01-17 05:46 UTC, JungangHighschool reviewed
class validator를 추가하시는 것도 나쁘지 않을 것 같습니다.

2023-01-17 14:32 UTC, k1g99 commented
> class validator를 추가하시는 것도 나쁘지 않을 것 같습니다.

아하! class-validator를 사용하는 것과 관련해서 목요일에 한 번 이야기 나눠보면 좋을 것 같습니다!

2023-01-18 04:53 UTC, jspark2000 commented on backend/src/reservation/reservation.module.ts
> +  providers: [ReservationService, PrismaService]
prisma 모듈이 global scope로 설정되어있기 때문에 providers에 PrismaService는 지우는게 좋을거 같습니다!

2023-01-18 12:54 UTC, k1g99 commented on backend/src/reservation/reservation.module.ts
> +  providers: [ReservationService, PrismaService]
아하, 반영하겠습니다!

2023-01-18 12:56 UTC, lshtar13 approved these changes

2023-01-19 05:03 UTC, Hyeongrok1 approved these changes

2023-01-19 11:36 UTC, SH9480P requested changes

2023-01-19 11:36 UTC, SH9480P commented on backend/src/reservation/reservation.dto.ts
> +}
1. members로 변경해주세요!
2. `member: Array<string>`보다 `members: string[]`이 더 타입스크립트스러울 것 같아요~
3. 클래스 이름은 PascalCase로 해주세요!
4. id는 dto로 받지 않습니다! dto는 POST request의 body로 전달되는 객체이니까요!

2023-01-19 11:36 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +    })
e 말고 더 명시적인 이름은 어떨까요?

2023-01-19 12:25 UTC, k1g99 commented on backend/src/reservation/reservation.dto.ts
> +}
네! 반영하겠습니다!

2023-01-19 12:26 UTC, k1g99 commented on backend/src/reservation/reservation.service.ts
> +    })
name이 좋겠네요!

2023-01-20 16:22 UTC, k1g99 commented
### 시간대별 인원 확인 기능 추가

최대 8명의 인원만 예약할 수 있도록 수정하였습니다. 
![image](https://user-images.githubusercontent.com/100272259/213750394-0e2a719f-c178-4b74-a543-95154cefa863.png)

-> 예약하려고 했던 시간 중에 1개의 time block (30분)이라도 8명을 초과한다면 ERROR를 던지도록 구현하였습니다.

2023-01-21 04:46 UTC, goo314 commented on backend/src/reservation/reservation.dto.ts
> +  purpose: string
아, 프론트엔드 쪽에서 참석자가 1명인 경우에는 purpose를 굳이 쓰지 않아도 된다고 생각해서 request로 보내지 않을 수 있어요!
예약 상세 정보 페이지에서 가장 아래 참석자가 1명인 경우에 purpose 공간에 이름 보여주는 것도 그 이유였어요 😃

<img width="510" alt="image" src="https://user-images.githubusercontent.com/62930375/213843785-95529d60-be7f-43d2-97e1-4a1fc03cc902.png">

아니면 빈 문자열을 request로 요청하는 것이 구현하는데 있어 편할까요 ?? 🤔🤔
( 프론트 쪽에서는 둘 중 상관없습니다 )

2023-01-21 16:36 UTC, SH9480P commented on backend/src/reservation/reservation.dto.ts
> +  purpose: string
@goo314
말씀해주신 경우를 위해 class-validator의 @isOptional() 데코레이터를 사용하여 purpose를 undefined로 받을 수 있게 하면 좋을 것 같네요. 그러면 프론트엔드에서는 purpose를 request body에 담지 않아도 되죠.

@k1g99 일건님, 위 답변 참고하셔서 CreateReservationDto의 purpose에 isOptional을 추가해주세요! isString은 그대로 유지해주시구요.
purpose가 undefined면 prisma로 create할 때 purpose는 query에 포함되지 않을겁니다.

2023-01-21 17:15 UTC, SH9480P approved these changes
고생하셨습니다! @goo314 님 코멘트 반영해서 수정하시고 바로 merge해주세요~

2023-01-23 10:18 UTC, k1g99 commented
> 고생하셨습니다! @goo314 님 코멘트 반영해서 수정하시고 바로 merge해주세요~

club을 enum으로 변경된 부분 반영하여 수정하려고 하는데 
``` typescript
enum Club { // 
  skkuding,
  skkud
}
```
```typescript
  @IsEnum(Club)
  club: Club
``` 
이렇게 작성하는 경우 `error TS2322: Type 'Club' is not assignable to type` 이라는 에러가 발생합니다...
club의 type관련된 문제인 것 같아서
```typescript
  @IsEnum(Club)
  club: any
``` 
이렇게 해보니 정상 작동합니다. 
혹시 club의 type은 어떻게 설정하는 게 맞을까요?

2023-01-23 11:14 UTC, SH9480P commented
(CreateReservationDto)

```
import { IsArray, IsEnum, IsString } from 'class-validator'
import { Club } from '@prisma/client'

export class CreateReservationRequestDto {
  @IsString()
  creator: string

  @IsEnum(Club)
  club: Club

  @IsString()
  startTime: string

  @IsString()
  endTime: string

  @IsString()
  purpose: string

  @IsArray()
  members: string[]
}

```
request body.club에 skkuding, skkud를 넣으면 response가 성공적으로 반환되고, 그 밖에 다른 문자열을 넣으면 다음과 같은 response를 받을 수 있었습니다.

> {
>     "statusCode": 400,
>     "message": [
>         "club must be one of the following values: skkuding, skkud"
>     ],
>     "error": "Bad Request"
> }

위와 같이 해도 안되면 vscode reload 해보시고, 그래도 안되면 comment 달아주세요~

2023-01-23 14:15 UTC, jspark2000 approved these changes

2023-01-26 11:14 UTC, merged