feat(fe): add list item
skkuding/skkuzzim pull request #48
Opened 2023-01-17 05:37 UTC by eunnbi

## 구현
ListItem 컴포넌트를 구현했습니다.
- 예약 상세 정보 조회에서 얻은 데이터를 props로 전달합니다.

![image](https://user-images.githubusercontent.com/89760088/212818070-35b3fae7-db8c-48a7-8ce3-950792983950.png)

close #13

2023-01-20 08:25 UTC, goo314 commented on frontend/src/components/ListItem.vue
> +  grid-template-columns: repeat(auto-fill, 45px);
참가자 이름이 4글자 이상 되면 띄어쓰기가 되네요! 영어인 경우는 이름이 서로 겹쳐버려요 🥲

<img width="813" alt="image" src="https://user-images.githubusercontent.com/62930375/213646639-341039e4-7259-415b-b262-1b5074481ab6.png">

2023-01-20 08:39 UTC, eunnbi commented on frontend/src/components/ListItem.vue
> +  grid-template-columns: repeat(auto-fill, 45px);
수정했습니다!
![image](https://user-images.githubusercontent.com/89760088/213652044-c718ea4c-9b92-433f-ac83-1d98e8fe71dc.png)

2023-01-21 09:01 UTC, goo314 commented on frontend/src/components/ListItem.vue
> +        <Button color="dark-red" @click="$emit('remove')">삭제</Button>
`id` 값도 emit 해주면 좋을 것 같아요!

2023-01-21 09:02 UTC, goo314 commented on frontend/src/components/ListItem.vue
> +        <Button color="dark-red" @click="$emit('remove')">삭제</Button>
근데 혹시 edit에 작은 따옴표가 아니라 backtick ` 인가요?

2023-01-22 00:07 UTC, eunnbi commented on frontend/src/components/ListItem.vue
> +        <Button color="dark-red" @click="$emit('remove')">삭제</Button>
> 근데 혹시 edit에 작은 따옴표가 아니라 backtick ` 인가요?

실수입니다 😅 작은 따옴표로 수정하겠습니다!

2023-01-22 06:05 UTC, eunnbi commented on frontend/src/components/ListItem.vue
> +        <Button color="dark-red" @click="$emit('remove')">삭제</Button>
`emits` 타입을 작성하려고 하는데 함수 파라미터에 `no-unused-vars`라고 eslint error가 뜹니다.
그래서 `no-unused-vars: off`를 eslint 파일에 추가해도 될까요??

![image](https://user-images.githubusercontent.com/89760088/213902965-c1d8faaa-bd6c-493e-9b52-b0aa696bdcc1.png)
```
'e' is defined but never used
'id' is defined but never used.
```

2023-01-22 06:14 UTC, goo314 commented on frontend/src/components/ListItem.vue
> +        <Button color="dark-red" @click="$emit('remove')">삭제</Button>
엇 일단 eslint 파일 말고 해당 코드에 주석처리 해주세요!
`// eslint-disable-next-line no-unused-vars`

2023-01-22 06:18 UTC, eunnbi commented on frontend/src/components/ListItem.vue
> +        <Button color="dark-red" @click="$emit('remove')">삭제</Button>
네!

2023-01-22 06:25 UTC, dotoleeoak commented on frontend/src/components/ListItem.vue
> +        <Button color="dark-red" @click="$emit('remove')">삭제</Button>
혹시 eslint config에서 `eslint:recommend` 지우면 어떻게 뜨나요?

https://github.com/skkuding/skkuzzim/blob/main/frontend/.eslintrc.cjs#L9-L14

2023-01-22 06:28 UTC, eunnbi commented on frontend/src/components/ListItem.vue
> +        <Button color="dark-red" @click="$emit('remove')">삭제</Button>
> 혹시 eslint config에서 `eslint:recommend` 지우면 어떻게 뜨나요?
> 
> https://github.com/skkuding/skkuzzim/blob/main/frontend/.eslintrc.cjs#L9-L14

지우면 에러가 안 뜹니다.

2023-01-22 06:37 UTC, dotoleeoak commented on frontend/src/components/ListItem.vue
> +        <Button color="dark-red" @click="$emit('remove')">삭제</Button>
그러면 그렇게 지우는 게 좋을 것 같아요! 아마 eslint-typescript config는 root에서 상속받을 거라 rules에 명시하지 않아도 될 거예요.

2023-01-22 06:40 UTC, eunnbi commented on frontend/src/components/ListItem.vue
> +        <Button color="dark-red" @click="$emit('remove')">삭제</Button>
네! 여기 브랜치에서 지우겠습니다.

2023-01-30 11:14 UTC, goo314 requested changes

2023-01-30 11:14 UTC, conakoo commented on frontend/src/components/ListItem.vue
> +  purpose?: string
type을 정의해서 prop은 item 1개로 받아오면 좋을 것 같아요!

2023-01-30 11:15 UTC, goo314 approved these changes

2023-01-30 11:16 UTC, merged