feat(be): add reservation update service
skkuding/skkuzzim pull request #50
Opened 2023-01-18 16:39 UTC by Hyeongrok1

### 예약 수정 API 구현

### 참고사항
- HTTP 메소드: PATCH
- URL: /reservation/:id

### Request Body 예시
```
{
    "creator": "조형록",
    "club": "SKKUDING",
    "startTime": "1970-01-01T00:00:00.000Z",
    "endTime": "1970-01-01T00:00:00.000Z",
    "purpose": "팬미팅",
    "members": ["조형록", "정대만" ]
}
```

### 수정 사항

**reservation.controller.ts**
```
async reserveUpdate(
    @Param('id', ParseIntPipe) id: number,
    @Body() updateInfo: UpdateReservationDto
  ) {
    return await this.reservationService.updateReservation(id, updateInfo)
  }
```
id를 @Param으로 받고 ParsIntPipe로 Validation하도록 수정했습니다.

**reservation.dto.ts**
```
import { IsString, IsDateString } from 'class-validator'

export class UpdateReservationDto {
  @IsString()
  creator: string
  @IsString()
  club: string
  @IsDateString()
  startTime: Date
  @IsDateString()
  endTime: Date
  @IsString()
  purpose: string
  @IsString({ each: true })
  members: string[]
}
```
class name을 수정하고, class-validator를 추가했습니다. 

### 2차 수정 사항 및 의견

제가 만든 UpdateReservationDto 클래스가 create service를 구현할 때 일건님께서 생성하신 CreateReservationRequestDto랑 사실상 같은데 둘을 합쳐도 상관없지 않을까요? 아니면 굳이 분리할 이유가 있을까요?

**reservation.service.ts**

피드백 받은대로 일건님이 작성하신 코드(같은 기능)을 참고하여 겹치는 시간대가 8명을 초과하면 에러를 던지도록 코드를 추가했습니다.

코드를 살펴보시고 혹시 더 고쳐야 할 부분이 있으면 피드백 부탁드립니다!

close #2

2023-01-19 04:28 UTC, JungangHighschool approved these changes

2023-01-19 12:05 UTC, SH9480P requested changes

2023-01-19 12:05 UTC, SH9480P commented on backend/src/reservation/reservation.dto.ts
> +}
1. Class name은 PascalCase로 해주세요
2. id는 넣지 않아도 됩니다
3. `member: Array<string>` 대신 `member: string[]`은 어떠신가요?
4. class-validator 사용해주세요~
5. members로 변경해주세요

2023-01-19 12:05 UTC, SH9480P commented on backend/src/reservation/reservation.controller.ts
> +}
id는 `@Param`으로 받고, ParseIntPipe로 validation 진행해주세요!

2023-01-19 12:05 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +  }
1. 단순히 수정하고자 하는 예약의 참가자 수만 체크하지 말고, 동시간대의 다른 예약도 고려해서 예외를 던져주세요.
2. 변수 이름은 camelCase로 통일하겠습니다. 
3. update하실 때 id와 updateTime은 넣을 필요 없습니다. id는 변하지 않을 거고, updateTime은 record가 수정되면 알아서 변경됩니다.
4. createMany하실 때 `data: data_array`로 하셔도 똑같지 않나요?
5. 변수 이름을 더 명시적으로 지어주세요. element보단 name이나 member가 보기에 더 좋아요.
6. 사용하지 않는 변수는 굳이 선언하지 않아도 됩니다.

2023-01-22 03:40 UTC, SH9480P requested changes

2023-01-22 03:40 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +    })
`id`가 아니고 `idWeFind` 아닌가요?

2023-01-22 03:40 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +    })
console.log 지워주세요~

2023-01-22 03:40 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +    }
new Error보단 HTTPException을 사용하시는게 어떨까요? 이를테면 BadRequest?
https://docs.nestjs.com/exception-filters#built-in-http-exceptions

2023-01-22 03:40 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +      },
Request body로부터 얻은 startTime이 1시 30분, endTime이 3시라고 해 봅시다. (어떤 사용자가 예약 시간을 1시 반부터 3시까지로 변경하고자 하는 경우)

위 쿼리를 사용하면 Reservation 테이블에서 조회되는 예약 건은 시작 시각이 1시 30분보다 늦고 종료 시각이 3시보다 이른 예약입니다.

그러나 우리는 1시 30분-3시에 겹치는 부분이 있는 모든 예약을 조회해야 합니다. 일부만 겹칠 수도 있고, 1시 30분-3시를 포함하는 예약도 있을 수 있죠.

#45 를 참고하시면 도움이 될 겁니다.

2023-01-22 03:47 UTC, Hyeongrok1 commented on backend/src/reservation/reservation.service.ts
> +      },
참고해서 고쳐보겠습니다!

2023-01-23 13:42 UTC, SH9480P approved these changes
> ### 2차 수정 사항 및 의견
> 제가 만든 UpdateReservationDto 클래스가 create service를 구현할 때 일건님께서 생성하신 CreateReservationRequestDto랑 사실상 같은데 둘을 합쳐도 상관없지 않을까요? 아니면 굳이 분리할 이유가 있을까요?

동의합니다!
다만 코드 가독성을 위해 DTO의 이름은 다르게 하는 것이 더 좋을 것 같다는 생각이 듭니다.
저라면 CreateReservationDto을 상속받는 UpdateResercationDto를 만들던지, typescript의 type alias을 사용하는 방식으로 내용은 동일하지만 이름은 다르게 사용하겠습니다.

위의 내용 관련해서 추가로 구현하실거면 commit 올려주시고, merge하셔도 좋을 것 같아요~

2023-01-23 14:13 UTC, jspark2000 approved these changes

2023-01-26 14:18 UTC, merged