feat(be): add reservation delete service
skkuding/skkuzzim pull request #52
Opened 2023-01-19 18:21 UTC by BEpaul

## 예약 삭제 API 구현

### 세부내용
HTTP METHOD: `DELETE`
URL: `~/reservation/:reservationId`

### 세부 구현 사항
1. reservation.controller.ts
  @Delete('/:id')
```typescript
  async deleteReservation(@Param('id') id: number) {
    return this.reservationService.deleteReservation(id)
  }
```

2. reservation.service.ts
```typescript
  async deleteReservation(id: number) {
    // relation 해제, member 삭제
    await this.prismaService.reservation.update({
      where: {
        id: Number(id)
      },
      data: {
        member: {
          deleteMany: {}
        }
      }
    })

    // reservation 삭제
    await this.prismaService.reservation.delete({
      where: {
        id: Number(id)
      }
    })

    return {
      'reservation id': id
    }
  }
```

### 논의 사항
회의 때 말씀하신 prisma schema에 onDelete 옵션을 주는 방법을 시도해보았으나, 공식 문서의 설명에는 테이블 간의 관계가 반대로 설정되어 있어 리팩토링하지 못했습니다. 즉, onDelete속성을 이용하면 예약을 삭제했을 때 그 안의 멤버 정보가 같이 삭제되는 것이 아니라, 멤버 한 명을 삭제 했을 때 예약이 삭제되었습니다.

Close #4

2023-01-20 05:42 UTC, SH9480P commented
> ### 논의 사항
> 회의 때 말씀하신 prisma schema에 onDelete 옵션을 주는 방법을 시도해보았으나, 공식 문서의 설명에는 테이블 간의 관계가 반대로 설정되어 있어 리팩토링하지 못했습니다. 즉, onDelete속성을 이용하면 예약을 삭제했을 때 그 안의 멤버 정보가 같이 삭제되는 것이 아니라, 멤버 한 명을 삭제 했을 때 예약이 삭제되었습니다.

![image](https://user-images.githubusercontent.com/64393421/213625505-b78cb40b-bcd4-4596-a299-7b44977a4da9.png)
이렇게 해 보시겠어요?

2023-01-21 17:21 UTC, SH9480P requested changes

2023-01-21 17:21 UTC, SH9480P commented on backend/src/reservation/reservation.controller.ts
> +  }
- `@Param('id', ParseIntPipe)`로 수정해주세요.
- await 붙여주세요!

2023-01-21 17:21 UTC, SH9480P commented on backend/src/reservation/reservation.dto.ts
> +}
지워주세요!

2023-01-21 17:21 UTC, SH9480P commented on backend/src/reservation/reservation.service.ts
> +      }
Controller에서 id를 url parameter로 받아올 때 ParseIntPipe를 붙이면 number형으로 형변환됩니다. 그러면 Number(id)를 사용할 필요가 없겠죠?

2023-01-26 07:31 UTC, BEpaul commented
> > ### 논의 사항
> > 회의 때 말씀하신 prisma schema에 onDelete 옵션을 주는 방법을 시도해보았으나, 공식 문서의 설명에는 테이블 간의 관계가 반대로 설정되어 있어 리팩토링하지 못했습니다. 즉, onDelete속성을 이용하면 예약을 삭제했을 때 그 안의 멤버 정보가 같이 삭제되는 것이 아니라, 멤버 한 명을 삭제 했을 때 예약이 삭제되었습니다.
> 
> ![image](https://user-images.githubusercontent.com/64393421/213625505-b78cb40b-bcd4-4596-a299-7b44977a4da9.png) 이렇게 해 보시겠어요?

2023-01-26 10:57 UTC, SH9480P approved these changes

2023-01-26 10:59 UTC, merged